services:
  flyway:
   image: flyway/flyway
   command: -url=jdbc:postgresql://localhost:1234/demo-crud -schemas=myschema -user=postgres -password=admin -connectRetries=1 migrate
   volumes:
     - .:/flyway/sql
   depends_on:
     - db
  db:
    image: postgres
    restart: always
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - 1234:5432
 