CREATE TYPE TIPO_PRODUTO AS ENUM ('REVENDA','MATERIAP','SERVICO');
CREATE CAST (CHARACTER VARYING as tipo_produto) WITH INOUT AS IMPLICIT;

ALTER TABLE PRODUTO
ADD COLUMN tipo TIPO_PRODUTO;

UPDATE PRODUTO
SET tipo = 'REVENDA';

CREATE TABLE ficha_materia_prima (
id UUID,
id_produto UUID REFERENCES produto(id) NOT NULL,
id_materia UUID REFERENCES produto(id) NOT NULL,
PRIMARY KEY (id_produto, id_materia));



